loadsheets:
  #- node:filepath
  - diagnosis: '/media/sf_VMShare/ConditionalTest/diagnosis.tsv'
  - file: '/media/sf_VMShare/ConditionalTest/file.tsv'
  - genomic_info: '/media/sf_VMShare/ConditionalTest/genomic_info.tsv'
  - image: '/media/sf_VMShare/ConditionalTest/image.tsv'
  - participant: '/media/sf_VMShare/ConditionalTest/participant.tsv'
  - program: '/media/sf_VMShare/ConditionalTest/program.tsv'
  - sample: '/media/sf_VMShare/ConditionalTest/sample.tsv'
  - study: '/media/sf_VMShare/ConditionalTest/study.tsv'
rulefile: './ExperimentalRuleSet.yml'
errorfile: '/media/sf_VMShare/ConditionalTest/RuleFileErrors.csv'
mdffiles:
  - 'https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/main/model-desc/cds-model.yml'
  - 'https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/main/model-desc/cds-model-props.yml'